local Chapter = {}
Chapter.__index = Chapter

local Constants = require('Constants')
local EventManager = require('EventManager')
local Log = require('Log').ForModule('Chapter')
local Shop = require('Shop')
local Ui = require('Ui')
local Utils = require('Utils')

------------------------------------------------------

Chapter.CHAPTER_SETUP = {
    [Constants.STANDARD] = {
        {
            chapter = 1,
            target = 6,
            enraged_boss = false,
        },
        {
            chapter = 1,
            target = 7,
            enraged_boss = false,
        },
        {
            chapter = 1,
            target = 8,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 10,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 12,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 14,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 17,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 20,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 23,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 27,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 31,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 35,
            enraged_boss = false,
        },
        {
            chapter = 5,
            target = 40,
            enraged_boss = true,
        },
        {
            chapter = 5,
            target = 45,
            enraged_boss = true,
        },
        {
            chapter = 5,
            target = 50,
            enraged_boss = true,
        },
    },
    [Constants.ADVANCED] = {
        {
            chapter = 1,
            target = 6,
            enraged_boss = false,
        },
        {
            chapter = 1,
            target = 8,
            enraged_boss = false,
        },
        {
            chapter = 1,
            target = 10,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 12,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 15,
            enraged_boss = false,
        },
        {
            chapter = 2,
            target = 18,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 21,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 25,
            enraged_boss = false,
        },
        {
            chapter = 3,
            target = 29,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 33,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 38,
            enraged_boss = false,
        },
        {
            chapter = 4,
            target = 43,
            enraged_boss = false,
        },
        {
            chapter = 5,
            target = 48,
            enraged_boss = true,
        },
        {
            chapter = 5,
            target = 54,
            enraged_boss = true,
        },
        {
            chapter = 5,
            target = 60,
            enraged_boss = true,
        },
    },
}

Chapter.snap_points = {}

function Chapter.init()
    Chapter.cacheObjects()

    -- Cache important snap points into a track
    Chapter.cacheTracks()

    Chapter.initUi()

    -- Reset scoring on marker movement
    EventManager.addHandler('onDrop', function(object)
        local level = Chapter.getCurrentLevel()
        local difficulty = Chapter.getCurrentDifficulty()
        Chapter.setupLevel(level, difficulty, true)
    end, Chapter.chapter_marker)

    for _, hourglass in ipairs(getObjectsWithTag(Constants.HOURGLASS)) do
        EventManager.addHandler('onRotate', function(object)
            -- Reset reroll track
            Chapter.snapToStep(Chapter.reroll_marker, 1)
        end, hourglass)
    end
end

function Chapter.cacheObjects()
    Chapter.score_board = getObjectsWithTag(Constants.SCORING_BOOK)[1]
    Chapter.chapter_board = getObjectsWithTag(Constants.CHAPTER_BOOK)[1]

    Chapter.score_marker = getObjectsWithTag(Constants.SCORE_MARKER)[1]
    Chapter.shop_marker = getObjectsWithTag(Constants.SHOP_MARKER)[1]
    Chapter.reroll_marker = getObjectsWithTag(Constants.REROLL_MARKER)[1]
    Chapter.chapter_marker = getObjectsWithTag(Constants.CHAPTER_MARKER)[1]

    if not Chapter.score_board or not Chapter.chapter_board or not Chapter.score_marker 
            or not Chapter.shop_marker or not Chapter.reroll_marker or not Chapter.chapter_marker then
        Log:error('Some objects are missing, please reload the mod without Mod Caching.')
        return
    end

    Chapter.bossDeckPosition = nil
    Chapter.bossDiscardPosition = nil
    Chapter.bossCurrentPosition = nil
    
    for _, snap in ipairs(Global.getSnapPoints()) do
        if Utils.contains(snap.tags, Constants.BOSS_DECK) then
            Chapter.bossDeckPosition = snap.position
        elseif Utils.contains(snap.tags, Constants.BOSS_DISCARD) then
            Chapter.bossDiscardPosition = snap.position
        elseif Utils.contains(snap.tags, Constants.BOSS_CURRENT) then
            Chapter.bossCurrentPosition = snap.position
        end
    end
end

function Chapter.cacheTracks()
    Chapter.snap_points[Constants.TRACK_START] = {}

    Chapter.snap_points[Constants.SCORE_TRACK] = {}
    Chapter.snap_points[Constants.SHOP_TRACK] = {}
    Chapter.snap_points[Constants.REROLL_TRACK] = {}

    for _, snap in ipairs(Chapter.score_board.getSnapPoints()) do
        -- Get the start if possible
        if Utils.contains(snap.tags, Constants.TRACK_START) then
            if Utils.contains(snap.tags, Constants.SCORE_TRACK) then
                Chapter.snap_points[Constants.TRACK_START][Constants.SCORE_TRACK] = snap
            elseif Utils.contains(snap.tags, Constants.SHOP_TRACK) then
                Chapter.snap_points[Constants.TRACK_START][Constants.SHOP_TRACK] = snap
            elseif Utils.contains(snap.tags, Constants.REROLL_TRACK) then
                Chapter.snap_points[Constants.TRACK_START][Constants.REROLL_TRACK] = snap
            end
        end

        -- Add the snap point to the track
        if Utils.contains(snap.tags, Constants.SCORE_TRACK) then
            table.insert(Chapter.snap_points[Constants.SCORE_TRACK], snap)
        elseif Utils.contains(snap.tags, Constants.SHOP_TRACK) then
            table.insert(Chapter.snap_points[Constants.SHOP_TRACK], snap)
        elseif Utils.contains(snap.tags, Constants.REROLL_TRACK) then
            table.insert(Chapter.snap_points[Constants.REROLL_TRACK], snap)
        end
    end

    -- Sort all tracks
    Chapter.snap_points[Constants.SCORE_TRACK] = 
                    Utils.sortByProximity(Chapter.snap_points[Constants.SCORE_TRACK],
                        Chapter.snap_points[Constants.TRACK_START][Constants.SCORE_TRACK])
    Chapter.snap_points[Constants.SHOP_TRACK] = 
                    Utils.sortByProximity(Chapter.snap_points[Constants.SHOP_TRACK],
                        Chapter.snap_points[Constants.TRACK_START][Constants.SHOP_TRACK])
    Chapter.snap_points[Constants.REROLL_TRACK] = 
                    Utils.sortByProximity(Chapter.snap_points[Constants.REROLL_TRACK],
                        Chapter.snap_points[Constants.TRACK_START][Constants.REROLL_TRACK])


    -- Same thing for the chapter book
    Chapter.snap_points[Constants.CHAPTER_TRACK] = {}

    for _, snap in ipairs(Chapter.chapter_board.getSnapPoints()) do
        if Utils.contains(snap.tags, Constants.TRACK_START) and Utils.contains(snap.tags, Constants.CHAPTER_TRACK) then
            Chapter.snap_points[Constants.TRACK_START][Constants.CHAPTER_TRACK] = snap
        end

        if Utils.contains(snap.tags, Constants.CHAPTER_TRACK) then
            table.insert(Chapter.snap_points[Constants.CHAPTER_TRACK], snap)
        end
    end

    Chapter.snap_points[Constants.CHAPTER_TRACK] = 
                    Utils.sortByProximity(Chapter.snap_points[Constants.CHAPTER_TRACK],
                        Chapter.snap_points[Constants.TRACK_START][Constants.CHAPTER_TRACK])
end

function Chapter.initUi()
    local root = Ui.createRootOnObject('chapter-control', Chapter.chapter_board, 2.5)
    root.scale = '0.1 0.1'

    local panel = root:panel({ id = 'main-panel', width = 2500, height = 600, x = -146, y = 260 })

    -- Transparent craft button
    Chapter.nextRound = panel:button({ id = 'next-round-button', text = 'Next Round', fontSize = 400,
        colors = Constants.BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR, active = false,
        onClick = function()
            local nextLevel = Chapter.getCurrentLevel() + 1
            if nextLevel == 15 then panel:hide() end
            if nextLevel >= 16 then return end

            Chapter.setupLevel(nextLevel, Chapter.getCurrentDifficulty())
        end
    })
end

function Chapter.displayUi()
    Chapter.nextRound:show()
end

function Chapter.setCurrentScore(score)
    Chapter.snapToStep(Chapter.score_marker, score + 1)
end

function Chapter.resetCurrentScore()
    Chapter.setCurrentScore(0)
end

function Chapter.resetShop()
    Chapter.snapToStep(Chapter.shop_marker, 1)
end

function Chapter.resetReroll()
    Chapter.snapToStep(Chapter.reroll_marker, 1)
end

function Chapter.setTargetScore(score)
    local targetScoreMarker = getObjectsWithTag(Constants.TARGET_MARKER)[1]

    Chapter.snapToStep(targetScoreMarker, score + 1)
end

function Chapter.getCurrentLevel()
    if Chapter.chapter_board.Book.getPage() >= 5 then
        return Chapter.getCurrentStep(Chapter.chapter_marker) 
                + 3 * (Chapter.chapter_board.Book.getPage() - Constants.ADVANCED_CHAPTER_OFFSET)
    else
        return Chapter.getCurrentStep(Chapter.chapter_marker) + (3 * Chapter.chapter_board.Book.getPage())
    end
end

function Chapter.getCurrentDifficulty()
    if Chapter.chapter_board.Book.getPage() >= 5 then
        return Constants.ADVANCED
    else
        return Constants.STANDARD
    end
end

function Chapter.getLevelDetails(difficulty, level)
    if difficulty ~= nil then
        return Chapter.CHAPTER_SETUP[difficulty][level]
    else
        return nil
    end
end

function Chapter.setLevel(level, difficulty)
    Chapter.snapToStep(Chapter.chapter_marker, level)

    -- For the chapter, also flip the book to the correct page
    if difficulty == Constants.STANDARD then
        Chapter.chapter_board.Book.setPage(math.floor((level-1) / 3))
    elseif difficulty == Constants.ADVANCED then
        Chapter.chapter_board.Book.setPage(math.floor((level-1) / 3) + Constants.ADVANCED_CHAPTER_OFFSET)
    end

    -- Set the score track to the correct side
    Chapter.score_board.Book.setPage(difficulty == Constants.STANDARD and 0 or 1)
end

function Chapter.setupLevel(level, difficulty, preventChapterSnap, preventBroadcast)
    if level < 1 or level > 16 then return end

    if not preventChapterSnap then
        Chapter.setLevel(level, difficulty, preventChapterSnap)
    end

    -- Set the score track to the correct side (done is setLevel already, could be changed)
    Chapter.score_board.Book.setPage(difficulty == Constants.STANDARD and 0 or 1)

    -- Reset score to 0
    Chapter.resetCurrentScore()

    -- Set target score based on chosen level
    local levelDetails = Chapter.getLevelDetails(difficulty, level)
    Chapter.setTargetScore(levelDetails.target)

    -- Flip all hourglass back
    for _, hourglass in ipairs(getObjectsWithTag(Constants.HOURGLASS)) do
        hourglass.setRotationSmooth({0, 180, 180})
    end

    -- Also reset the shop and reroll tracks
    Chapter.snapToStep(Chapter.shop_marker, 1)
    Chapter.snapToStep(Chapter.reroll_marker, 1)

    -- And close the shop
    Shop.closeShop()

    -- Flip a new boss and discard the old one, if any
    if level % 3 == 1 then
        -- Discard the current boss card if any
        local bossCard = Utils.getFirstElementAbovePosition(Vector(Chapter.bossCurrentPosition) - Vector(0, 1, 0), Constants.BOSS_CARD)
        if bossCard then
            bossCard.setPositionSmooth(Vector(Chapter.bossDiscardPosition) + Vector(0, 1, 0), false, true)
            bossCard.setRotationSmooth({0, 180, 180}, false, true)
        end

        -- Draw a new one
        local bossDeck = Utils.getFirstElementAbovePosition(Vector(Chapter.bossDeckPosition) - Vector(0, 1, 0), Constants.BOSS_CARD)
        if not bossDeck then return end

        if bossDeck.type == 'Card' then
            bossDeck.setPositionSmooth(Vector(Chapter.bossCurrentPosition) + Vector(0, 1, 0), false, true)
            bossDeck.setRotationSmooth(Constants.BOSS_ORIENTATION[levelDetails.enraged_boss], false, true)
        else
            bossDeck.takeObject({
                position = Vector(Chapter.bossCurrentPosition) + Vector(0, 1, 0),
                rotation = Constants.BOSS_ORIENTATION[levelDetails.enraged_boss],
                smooth = true,
            })
        end
    end

    if not preventBroadcast then
        if level % 3 == 0 then
            if levelDetails.enraged_boss then
                broadcastToAll('Enraged boss round!', Color.Red)
            else
                broadcastToAll('Boss round!', Color.Blue)
            end

            -- Ping the boss
            Player.getPlayers()[1].pingTable(Chapter.bossCurrentPosition)
        else
            broadcastToAll('New round start', Color.Yellow)
        end
    end
end

function Chapter.snapToStep(marker, step)
    if not marker or not step or step < 1 then return end

    local markerType = Chapter.getMarkerType(marker)
    if not markerType then return end

    local track = Chapter.snap_points[markerType]
    local trackObject = Chapter.getTrackObject(markerType)

    local physicalStep = step
    if(markerType == Constants.CHAPTER_TRACK) then
        physicalStep = (step - 1) % 3 + 1
    end

    if not track[physicalStep] then
        Log:error('Could not snap %s to step %d, out of bounds.', markerType, physicalStep)
        return
    end
    
    -- Small y offset to avoid getting stuck in the boards
    local offset = Vector(0, 0.25, 0)

    marker.setPositionSmooth(trackObject.positionToWorld(track[physicalStep].position) + offset, false, true)
end

function Chapter.getCurrentStep(marker)
    if not marker then return end

    local markerType = Chapter.getMarkerType(marker)
    if not markerType then return end

    local snapTrack = Chapter.snap_points[markerType]
    if not snapTrack then return end

    -- Otherwise find the closest snap point on the corresponding track
    local position = marker.getPosition()
    local closestIndex, closestDistance = nil, nil

    local trackObject = Chapter.getTrackObject(markerType)
    for index, snap in ipairs(snapTrack) do
        local distance = (Vector(position) - Vector(trackObject.positionToWorld(snap.position))):magnitude()

        if closestDistance == nil or distance < closestDistance then
            closestIndex = index
            closestDistance = distance
        end
    end

    if closestIndex ~= nil then
        Log:debug('Detected %s as step %d.', markerType, closestIndex)
        return closestIndex
    else
        return nil
    end
end

function Chapter.getMarkerType(marker)
    if not marker then return nil end

    -- Not a marker
    if not Utils.contains(marker.getTags(), Constants.MARKER) then
        return nil
    end

    if Utils.contains(marker.getTags(), Constants.SCORE_TRACK) then
        return Constants.SCORE_TRACK
    elseif Utils.contains(marker.getTags(), Constants.SHOP_TRACK) then
        return Constants.SHOP_TRACK
    elseif Utils.contains(marker.getTags(), Constants.REROLL_TRACK) then
        return Constants.REROLL_TRACK
    elseif Utils.contains(marker.getTags(), Constants.CHAPTER_TRACK) then
        return Constants.CHAPTER_TRACK
    end

    return nil
end

function Chapter.getTrackObject(markerType)
    if markerType == Constants.SCORE_TRACK or markerType == Constants.SHOP_TRACK 
                or markerType == Constants.REROLL_TRACK then
        return Chapter.score_board
    elseif markerType == Constants.CHAPTER_TRACK then
        return Chapter.chapter_board
    else
        return nil
    end

end

function Chapter.getShopMarker()
    return Chapter.shop_marker
end

function Chapter.save()
    local flatSetup = {}

    return flatSetup
end

------------------------------------------------------

return {
    init = Chapter.init,
    save = Chapter.save,
    displayUi = Chapter.displayUi,
    resetCurrentScore = Chapter.resetCurrentScore,
    setTargetScore = Chapter.setTargetScore,
    resetShop = Chapter.resetShop,
    resetReroll = Chapter.resetReroll,
    setLevel = Chapter.setLevel,
    setupLevel = Chapter.setupLevel,
    getCurrentLevel = Chapter.getCurrentLevel,
    getLevelDetails = Chapter.getLevelDetails,
    getCurrentStep = Chapter.getCurrentStep,
    getShopMarker = Chapter.getShopMarker,
    snapToStep = Chapter.snapToStep,
}
