local Constants = {}
Constants.__index = Constants

------------------------------------------------------

-- Logging
Constants.DEBUG = 1
Constants.INFO = 2
Constants.WARNING = 3
Constants.ERROR = 4
Constants.NONE = 5

-- Color palette --
Constants.TEXT_COLOR = '#ff4c4cff'
Constants.BUTTON_TEXT_COLOR = '#3b2b30ff'
Constants.BUTTON_BACKGROUND_COLOR = '#ff4c4cff'
Constants.GLOBAL_BUTTON_ON_COLOR = '#fd3838ff'
Constants.GLOBAL_BUTTON_OFF_COLOR = '#a12d2dff'
Constants.BUTTON_BACKGROUND_COLORS = '#FFFFFF|#c2c2c2ff|#FFFFFF|#c74040ff'
Constants.GLOBAL_BUTTON_BACKGROUND_COLORS = Constants.GLOBAL_BUTTON_OFF_COLOR .. '|#ff4e4eff|#c43d3dff|#a77b7b99'
Constants.BACKGROUND_COLOR = '#242424ff'

-- Tags

------------------------------------------------------

return Constants