local Constants = {}
Constants.__index = Constants

------------------------------------------------------

-- Logging
Constants.DEBUG = 1
Constants.INFO = 2
Constants.WARNING = 3
Constants.ERROR = 4
Constants.NONE = 5

-- Color palette --
-- Constants.TEXT_COLOR = '#ff4c4cff'
-- Constants.BUTTON_TEXT_COLOR = '#3b2b30ff'
-- Constants.BUTTON_BACKGROUND_COLOR = '#ff4c4cff'
-- Constants.BUTTON_DESELECTED_COLOR = '#832929ff'
-- Constants.GLOBAL_BUTTON_ON_COLOR = '#fd3838ff'
-- Constants.GLOBAL_BUTTON_OFF_COLOR = '#a12d2dff'
-- Constants.BUTTON_BACKGROUND_COLORS = '#FFFFFFFF|#c2c2c2ff|#FFFFFFFF|#c74040ff'
-- Constants.GLOBAL_BUTTON_BACKGROUND_COLORS = Constants.GLOBAL_BUTTON_OFF_COLOR .. '|#ff4e4eff|#c43d3dff|#a77b7b99'
-- Constants.BACKGROUND_COLOR = '#242424ff'

Constants.BACKGROUND_COLOR = '#131A24FF'
Constants.PANEL_BACKGROUND_COLOR = '#233447FF'
Constants.BUTTON_BACKGROUND_COLOR = '#3b5c75ff'
Constants.BUTTON_DESELECTED_COLOR = '#19364dff'
Constants.BUTTON_BACKGROUND_COLORS = Constants.BUTTON_BACKGROUND_COLOR .. '#48708DFF|#42729eff|#7b93a799'
Constants.BUTTON_TEXT_COLOR = '#F3F6F8FF'
Constants.TEXT_COLOR = '#F5F4F0FF'
Constants.MUSHROOM_TEXT_COLOR = '#784fc5ff'
Constants.COIN_TEXT_COLOR = '#c5a84f'
Constants.POTION_TEXT_COLOR = '#4cb3d3ff'

-- Difficulties
Constants.STANDARD = 'Standard'
Constants.ADVANCED = 'Advanced'

-- Tags
Constants.CHAPTER_MARKER = 'ChapterMarker'
Constants.TARGET_MARKER = 'TargetMarker'
Constants.SCORE_MARKER = 'ScoreMarker'
Constants.SHOP_MARKER = 'ShopMarker'
Constants.REROLL_MARKER = 'RerollMarker'
Constants.SHOP_DECK = 'ShopDeck'
Constants.SHOP_CURRENT = 'ShopCurrent'
Constants.SHOP_DISCARD = 'ShopDiscard'
Constants.RED = 'Red'
Constants.PURPLE = 'Purple'
Constants.GREEN = 'Green'
Constants.DIE = 'Die'
Constants.HOURGLASS = 'Hourglass'
Constants.CHAPTER_BOOK = 'ChapterBook'
Constants.SCORING_BOOK = 'ScoringBook'
Constants.CHAPTER_TRACK = 'ChapterTrack'
Constants.SCORE_TRACK = 'ScoreTrack'
Constants.SHOP_TRACK = 'ShopTrack'
Constants.REROLL_TRACK = 'RerollTrack'
Constants.TRACK_START = 'TrackStart'
Constants.MARKER = 'Marker'
Constants.BOSS_DECK = 'BossDeck'
Constants.BOSS_DISCARD = 'BossDiscard'
Constants.BOSS_CURRENT = 'BossCurrent'
Constants.BOSS_REWARD_DECK = 'BossRewardDeck'
Constants.BOSS_REWARD_CURRENT = 'BossRewardCurrent'
Constants.BOSS_CARD = 'BossCard'
Constants.BOSS_REWARD_CARD = 'BossRewardCard'
Constants.SHOP_CARD = 'ShopCard'
Constants.MUSHROOM_BAG = 'MushroomBag'
Constants.MUSHROOM_TILE = 'MushroomTile'
Constants.MUSHROOM = 'Mushroom'
Constants.MUSHROOM_1 = 'Mushroom1'
Constants.MUSHROOM_5 = 'Mushroom5'
Constants.COIN_BAG = 'CoinBag'
Constants.COIN_TILE = 'CoinTile'
Constants.COIN = 'Coin'
Constants.COIN_1 = 'Coin1'
Constants.COIN_5 = 'Coin5'
Constants.POTION_BAG = 'PotionBag'
Constants.POTION_TILE = 'PotionTile'
Constants.POTION = 'Potion'
Constants.POTION_1 = 'Potion1'
Constants.POTION_3 = 'Potion3'
Constants.FACE_CRAFT = 'FaceCraft'
Constants.CRAFTING_STATION = 'CraftingStation'
Constants.SHOP_ANCHOR = 'ShopAnchor'
Constants.SHOP_EXTRA = 'ShopExtra'
Constants.RESULT_TABLEAU = 'ResultTableau'

-- Effects
Constants.EFFECT_EXTRA_RED_SHOP_SLOT = 'extraRedShopSlot'
Constants.EFFECT_EXTRA_GREEN_SHOP_SLOT = 'extraGreenShopSlot'
Constants.EFFECT_EXTRA_PURPLE_SHOP_SLOT = 'extraPurpleShopSlot'
Constants.EFFECT_DOUBLE_POTION_INCOME = 'doublePotionIncome'
Constants.EFFECT_BLOCK_COIN_INCOME = 'blockCoinIncome'
Constants.EFFECT_MINUS_1_DIE_REROLL_PRICE = 'minus1DieRerollPrice'

Constants.ADVANCED_CHAPTER_OFFSET = 5

-- true = enraged
Constants.BOSS_ORIENTATION = {
    [false] = {0.00, 180.00, 0.00},
    [true] = {0.00, 0.00, 0.00}
}

------------------------------------------------------

return Constants