local GlobalUi = {}
GlobalUi.__index = GlobalUi

local Constants = require('Constants')
local EventManager = require('EventManager')
local Log = require('Log').ForModule('GlobalUi')
local Options = require('Options')
local Setup = require('Setup')
local Ui = require('Ui')

------------------------------------------------------

function GlobalUi.init()
    -- Do not show the UI if we've selected a manual setup previously
    if Options.isManualSetup() then
        return
    end

    assert(Ui.getRoot() ~= nil)

    GlobalUi.ui = {}
    GlobalUi.first_setup_click = true

    GlobalUi.initStartUi()
    GlobalUi.initSetupUi()
end

function GlobalUi.initStartUi()
    GlobalUi.ui.start_ui = {}
    local startUi = GlobalUi.ui.start_ui

    -- Setup choice
    startUi.menu_panel = Ui.getRoot():verticalLayout({ 
        id = 'menu-panel', width = 300, height = 150, x = 130, y = -10, color = Constants.BACKGROUND_COLOR, active = false
    })
    startUi.menu_panel.attributes.raycastTarget = true
    startUi.menu_panel.attributes.allowDragging = true
    startUi.menu_panel.attributes.returnToOriginalPositionWhenReleased = false

    local text = startUi.menu_panel:text({
        id = 'choose-setup-type', text = 'Choose a setup', fontSize = 30, fontStyle = 'Bold', color = Constants.TEXT_COLOR,
    })
    local buttonLayout = startUi.menu_panel:horizontalLayout({
        id = 'setup-button-hl', height = 50, padding = '10 10 0 10', spacing = 10,
    })

    startUi.scripted_setup_button = buttonLayout:button({ 
        id = 'scripted-setup-button', text = 'Scripted', fontSize = 30, 
        color = Constants.BUTTON_BACKGROUND_COLOR, textColor = Constants.BUTTON_TEXT_COLOR,
        onClick = function() 
            if GlobalUi.first_setup_click == true then
                broadcastToAll('Make sure all players are seated, then click again.', Color.Yellow)
                GlobalUi.first_setup_click = false
            else
                GlobalUi.showSetup()
            end
        end, })

    startUi.manual_setup_button = buttonLayout:button({ 
        id = 'manual-setup-button', text = 'Manual', fontSize = 30, 
        color = Constants.BUTTON_BACKGROUND_COLOR, textColor = Constants.BUTTON_TEXT_COLOR,
        onClick = function()
            Log:debug('Manual setup selected, wiping everything')
            Options.setup_complete = true
            Options.manual_setup = true

            Ui.getRoot():fullWipe()
            EventManager.wipeAllHandlers()
        end,
    })
end

function GlobalUi.initSetupUi()
    GlobalUi.ui.setup_ui = {}
    local setupUi = GlobalUi.ui.setup_ui

    -----------------
    -- Main Panel  --
    -----------------
    setupUi.setup_panel = Ui.getRoot():verticalLayout({ 
        id = 'setup-panel', width = 640, height = 280, x = 0, y = 0, color = Constants.BACKGROUND_COLOR, 
        padding = '40 40 20 20', spacing = 20, rectAlignment = 'MiddleCenter', active = false
    })
    setupUi.setup_panel.attributes.raycastTarget = true
    setupUi.setup_panel.attributes.allowDragging = true
    setupUi.setup_panel.attributes.returnToOriginalPositionWhenReleased = false
    setupUi.setup_panel.attributes.childForceExpandHeight = false

    local title = setupUi.setup_panel:text({
        id = 'setup-panel-title', text = 'Select the setup options', fontSize = 25, fontStyle = 'Bold', 
        color = Constants.TEXT_COLOR, height = 60,
    })

    ------------------
    -- Main options --
    ------------------

    local difficultyToggle = setupUi.setup_panel:toggleGroup({ id = 'difficulty-toggle', height = 65, })
    local difficultyHl = difficultyToggle:horizontalLayout({ 
        id = 'difficulty-hl', spacing = 30, rectAlignment = 'MiddleCenter',
    })

    local difficultyText = difficultyHl:text({
        id = 'difficulty-text', text = 'Difficulty:', fontSize = 30, color = Constants.TEXT_COLOR, width = 40,
        alignment = 'MiddleLeft',
    })

    local normalDifficultyToggle = difficultyHl:toggleButton({
        id = 'normal-difficulty', text = Constants.NORMAL, fontSize = 30,
        colors = Constants.GLOBAL_BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR,
        isOn = (Options.selected_difficulty == Constants.NORMAL or Options.selected_difficulty == nil),
        onValueChanged = function(_, isOn) 
            if isOn == 'True' then
                Options.selected_difficulty = Constants.NORMAL
            end
        end
    })
    normalDifficultyToggle.attributes.selectedBackgroundColor = Constants.BUTTON_BACKGROUND_COLOR
    normalDifficultyToggle.attributes.deselectedBackgroundColor = Constants.BUTTON_DESELECTED_COLOR

    local advancedDifficultyToggle = difficultyHl:toggleButton({
        id = 'advanced-difficulty', text = Constants.ADVANCED, fontSize = 30,
        colors = Constants.GLOBAL_BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR,
        isOn = (Options.selected_difficulty == Constants.ADVANCED),
        onValueChanged = function(_, isOn) 
            if isOn == 'True' then
                Options.selected_difficulty = Constants.ADVANCED
            end
        end
    })
    advancedDifficultyToggle.attributes.selectedBackgroundColor = Constants.BUTTON_BACKGROUND_COLOR
    advancedDifficultyToggle.attributes.deselectedBackgroundColor = Constants.BUTTON_DESELECTED_COLOR

    ------------------
    -- Setup button --
    ------------------
    local setupButtonPanel = setupUi.setup_panel:panel({ 
        id = 'setup-button-hl', height = 90
    })
    local setupButton = setupButtonPanel:button({ 
        id = 'start-setup-button', text = 'Setup', fontSize = 30, width = 200, height = 65, 
        rectAlignment = 'MiddleCenter', colors = Constants.BUTTON_BACKGROUND_COLORS, 
        color = Constants.BUTTON_BACKGROUND_COLOR,
        textColor = Constants.BUTTON_TEXT_COLOR, onClick = function() 
            if #getSeatedPlayers() < 1 then
                broadcastToAll('At least one player must be seated to start the game.', Color.Red)
                return
            end

            Log:info('Starting scripted setup with options:\n  difficulty = %s\n',
                tostring(Options.selected_difficulty))
            Options.manual_setup = false
            setupUi.setup_panel:hide()
            Setup.setup()
        end,
    })

    setupButton.attributes.fontStyle = 'Bold'
end

function GlobalUi.showSetup()
    GlobalUi.ui.start_ui.menu_panel:hide()
    GlobalUi.ui.setup_ui.setup_panel:show()
end

function GlobalUi.showMenu()
    GlobalUi.ui.setup_ui.setup_panel:hide()
    GlobalUi.ui.start_ui.menu_panel:show()
end

function GlobalUi.save()
    local flatData = {}

    return flatData
end

------------------------------------------------------

return {
    init = GlobalUi.init,
    save = GlobalUi.save,
    showMenu = GlobalUi.showMenu,
    showSetup = GlobalUi.showSetup,
}
