-- This project uses Benjamin-Dobell/luabundle git repo to organise this project

-- Naming conventions, hopefully that's understandable
-- Classes: PascalCase
-- Functions: camelCase
-- Global vars: underscore: CONSTANTS_LIKE_THIS and variables_like_this
-- Local vars: camelCase

-- TODO: Have one extra slot per result row, in case we get the +1? might cause issues
-- TODO: Only reset die reroll if flipping hourglass face down?
-- TODO: Add counter UI to the score?
-- TODO: On next round press, ping all torches? and chat message warning
-- TODO: Result summer -> button to add +1 every time your click (+5 on middle click), then apply it to the score marker when pressing ok?
-- TODO: Add chat message "Player gained X coins" delayed after using the tile counter (need to take into account manual changes as well I think)
-- TODO: Add reroll button next to the potion tile to automate reroll cost?
-- TODO: Chapter has enrage_boss even on sections with no boss. Also need enrage_true on round 1 of the chapter to be able to draw an enraged boss
-- TODO: Handle the case where multiple cards per color are possible in shop extra slots above? might only need the one extra slot
-- TODO: Discard face up might be more convenient
-- TODO: Detect when current score > target?
-- TODO: Click on income icon for income? or use the shop UI maybe? or above the next round button

-- IDEA: Add interest between brackets
-- IDEA: check we have 3 coins and 3 potions still during setup?
-- IDEA: might need to keep open/closed shop status between saves (for rollbacks)
-- IDEA: think of a way to implement auto detect for all effects, auto roll and auto count etc I'm sure it's possible honestly (but should it?)

local Chapter = require('Chapter')
local Constants = require('Constants')
local CraftingStation = require('CraftingStation')
local EventManager = require('EventManager')
_G.EventManager = EventManager  -- for reflection/debugging access
local GlobalUi = require('GlobalUi')
local Log = require('Log').ForModule('Global')
local Options = require('Options')
local ResourceCounter = require('ResourceCounter')
local ResultTableau = require('ResultTableau')
local Shop = require('Shop')
local Ui = require('Ui')

------------------------------------------------------

local NOT_INTERACTABLE = {
    -- '',
}

function onLoad(script_state)
    -- Random seed with a couple of fake numbers
    math.randomseed(os.time())
    math.random(); math.random(); math.random()

    -- Disable non-interactable objects
    for _, objectGUID in ipairs(NOT_INTERACTABLE) do
        getObjectFromGUID(objectGUID).interactable = false
    end

    -- Parse save data
    local savedData = JSON.decode(script_state) or {}
    -- Uncomment this to wipe it at the start
    -- local savedData = {}

    Log.init()
    EventManager.init(savedData.event_manager or {})
    Ui.init()
    Options.init(savedData.options or {})
    GlobalUi.init()
    Chapter.init()
    ResourceCounter.init()
    CraftingStation.init()
    Shop.init()
    ResultTableau.init()
    
    if not Options.isManualSetup() then
        Ui.globalRefresh()

        if Options.isSetupComplete() then
            Chapter.displayUi()
            Shop.displayUi()

            broadcastToAll('Game loaded', Color.Green)
        else
            Wait.frames(function()
                GlobalUi.showMenu()
            end, 20)
        end
    end
end

function onSave()
    local dataToSave = {}

    if Options.isSetupComplete() then
        dataToSave.options = Options.save()
    end

    return JSON.encode(dataToSave)
end

function handleEvent(data)
    return EventManager.handleObjectEvent(data)
end
