local MushroomCounter = {}
MushroomCounter.__index = MushroomCounter

local Constants = require('Constants')
local EventManager = require('EventManager')
local Log = require('Log').ForModule('MushroomCounter')
local Ui = require('Ui')
local Utils = require('Utils')

------------------------------------------------------

function MushroomCounter.init()
    MushroomCounter.initUi()

    EventManager.addHandler('onObjectDrop', function(_, object)
        if Utils.contains(object.getTags(), Constants.MUSHROOM) then
            MushroomCounter.updateCounters()
        end
    end)
end

function MushroomCounter.initUi()
    local mushroomTiles = getObjectsWithTag(Constants.MUSHROOM_TILE)
    MushroomCounter.counters = {}

    for index, tile in ipairs(mushroomTiles) do
        local mushroomTileRoot = Ui.createRootOnObject('luminary-board', tile, 1.2)
        mushroomTileRoot.scale = '0.1 0.1'

        local panel = mushroomTileRoot:panel({ id = 'main-panel', width = 1000, height = 700, x = 200, y = 0 })
        MushroomCounter.counters[tile.getGUID()] = panel:text({ id = 'counter', text = '0', fontSize = 600, color = 'White', })
    end
end

function MushroomCounter.updateCounters()
    local mushroomTiles = getObjectsWithTag(Constants.MUSHROOM_TILE)

    for _, tile in ipairs(mushroomTiles) do
        local counter = MushroomCounter.counters[tile.getGUID()]

        if counter then
            local hitObjects = Utils.getObjectsAboveElement(tile, Constants.MUSHROOM)
            local total = 0

            for _, mushroom in ipairs(hitObjects) do
                if Utils.contains(mushroom.getTags(), Constants.MUSHROOM_1) then
                    total = total + 1
                elseif Utils.contains(mushroom.getTags(), Constants.MUSHROOM_5) then
                    total = total + 5
                end
            end

            counter:setText(tostring(total))
        end
    end
end

function MushroomCounter.save()
    local flatSetup = {}

    return flatSetup
end

------------------------------------------------------

return {
    init = MushroomCounter.init,
    save = MushroomCounter.save,
    updateCounters = MushroomCounter.updateCounters,
}
