local Options = {}
Options.__index = Options

local Constants = require('Constants')

------------------------------------------------------

function Options.init(savedData)
    Options.setup_complete = savedData.setup_complete or false
    Options.manual_setup = savedData.manual_setup or false

    Options.selected_difficulty = savedData.selected_difficulty or Constants.NORMAL
end

function Options.isSetupComplete()
    return Options.setup_complete
end

function Options.isManualSetup()
    return Options.manual_setup
end

function Options.getDifficulty()
    return Options.selected_difficulty
end

function Options.save()
    local flatSetup = {}

    flatSetup.setup_complete = Options.setup_complete
    flatSetup.manual_setup = Options.manual_setup

    flatSetup.selected_difficulty = Options.selected_difficulty

    return flatSetup
end

------------------------------------------------------

return Options
