local Setup = {}
Setup.__index = Setup

local Chapter = require('Chapter')
local Constants = require('Constants')
local Options = require('Options')
local Log = require('Log').ForModule('Setup')
local Shop = require('Shop')
local Utils = require('Utils')

------------------------------------------------------

function Setup.setup()
    Log:info('Setting up game')

    -- Get important elements
    local bossDeck = nil
    local redShopDeck = nil
    local purpleShopDeck = nil
    local greenShopDeck = nil
    local bossRewardDeck = nil
    for _, snap in ipairs(Global.getSnapPoints()) do
        if Utils.contains(snap.tags, Constants.BOSS_DECK) then
            bossDeck = Utils.getFirstElementAbovePosition(snap.position + Vector(0, -1, 0), Constants.BOSS_CARD)
        elseif Utils.contains(snap.tags, Constants.SHOP_DECK) then
            if Utils.contains(snap.tags, Constants.RED) then
                redShopDeck = Utils.getFirstElementAbovePosition(snap.position + Vector(0, -1, 0), Constants.SHOP_CARD)
            elseif Utils.contains(snap.tags, Constants.PURPLE) then
                purpleShopDeck = Utils.getFirstElementAbovePosition(snap.position + Vector(0, -1, 0), Constants.SHOP_CARD)
            elseif Utils.contains(snap.tags, Constants.GREEN) then
                greenShopDeck = Utils.getFirstElementAbovePosition(snap.position + Vector(0, -1, 0), Constants.SHOP_CARD)
            end
        elseif Utils.contains(snap.tags, Constants.BOSS_REWARD_DECK) then
            bossRewardDeck = Utils.getFirstElementAbovePosition(snap.position + Vector(0, -1, 0), Constants.BOSS_REWARD_CARD)
        end
    end

    -- Shuffle everything
    bossDeck.shuffle()
    redShopDeck.shuffle()
    purpleShopDeck.shuffle()
    greenShopDeck.shuffle()
    bossRewardDeck.shuffle()

    -- Set the target score to the appropriate value based on the selected difficulty
    local level = 1
    local levelDetail = Chapter.getLevelDetails(Options.getDifficulty(), level)
    Chapter.setupLevel(level, Options.getDifficulty())

    Chapter.displayUi()
    Shop.displayUi()

    Wait.time(function()
        Options.setup_complete = true
        Options.manual_setup = false

        Log:info('Setup complete')
        Log:debug('Options:')
        Log:debug('    - difficulty: ' .. tostring(Options.getDifficulty()))
        broadcastToAll('Setup complete!', Color.Green)
    end, 1)
end

------------------------------------------------------

return {
    setup = Setup.setup,
}