local Shop = {}
Shop.__index = Shop

local Chapter
local Constants = require('Constants')
local EventManager = require('EventManager')
local Log = require('Log').ForModule('Shop')
local ResourceCounter = require('ResourceCounter')
local ResultTableau = require('ResultTableau')
local Ui = require('Ui')
local Utils = require('Utils')

------------------------------------------------------

function Shop.init()
    Chapter = require('Chapter')

    Shop.anchor = getObjectsWithTag(Constants.SHOP_ANCHOR)[1]
    if not Shop.anchor then
        Log.error('Shop anchor not found.')
        return
    end

    -- Get the current discard/slot positions per color, as well as each shop deck position
    Shop.positions = {
        [Constants.RED] = { discard = nil, slot = nil, extra_slot = nil, deck = nil },
        [Constants.GREEN] = { discard = nil, slot = nil, extra_slot = nil, deck = nil },
        [Constants.PURPLE] = { discard = nil, slot = nil, extra_slot = nil, deck = nil },
    }

    local colors = { Constants.RED, Constants.GREEN, Constants.PURPLE }
    local typePerTag = {
        [Constants.SHOP_DISCARD] = 'discard',
        [Constants.SHOP_CURRENT] = 'slot',
        [Constants.SHOP_EXTRA]   = 'extra',
        [Constants.SHOP_DECK]    = 'deck',
    }

    for _, snap in ipairs(Global.getSnapPoints()) do
        -- If this snap matches any shop-related tag, assign positions per color
        for tag, role in pairs(typePerTag) do
            if Utils.contains(snap.tags, tag) then
                for _, color in ipairs(colors) do
                    if Utils.contains(snap.tags, color) then
                        -- Duplicate warning
                        if Shop.positions[color][role] then
                            Log:error('Overwriting %s for %s', tostring(role), tostring(color))
                        end
                        Shop.positions[color][role] = snap.position
                    end
                end
            end
        end
    end

    -- Ensure required positions exist
    for _, color in ipairs(colors) do
        if not Shop.positions[color].deck then
            Log:error('Missing SHOP_DECK snap for color %s.', tostring(color))
        end
        if not Shop.positions[color].slot then
            Log:error('Missing SHOP_CURRENT snap for color %s.', tostring(color))
        end
        if not Shop.positions[color].discard then
            Log:info('Missing SHOP_DISCARD snap for color %s.', tostring(color))
        end
        if not Shop.positions[color].extra_slot then
            Log:info('Missing SHOP_EXTRA snap for color %s.', tostring(color))
        end
    end

    Shop.initUi()
end

function Shop.initUi()
    local root = Ui.createRootOnObject('shop-anchor', Shop.anchor, 2)
    root.scale = '0.1 0.1'

    local panel = root:verticalLayout({ id = 'main-panel', width = 3000, height = 2000, y = 0, spacing = 100, })
    panel.attributes.childForceExpandHeight = false
    panel.attributes.childAlignment = 'MiddleCenter'

    -- Open shop button
    Shop.openShopButton = panel:button({ id = 'open-shop-button', text = 'Open Shop', fontSize = 600,
        height = 1000,
        colors = Constants.BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR, 
        active = false, onClick = function()
            Shop.openShop()
        end
    })

    Shop.closeShopButton = panel:button({ id = 'close-shop-button', text = 'Close Shop', fontSize = 600,
        height = 1000,
        colors = Constants.BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR, 
        active = false, onClick = function()
            Shop.closeShop()
        end
    })

    Shop.rerollShopButton = panel:button({ id = 'reroll-shop-button', text = 'Reroll Shop', fontSize = 600,
        height = 1000,
        colors = Constants.BUTTON_BACKGROUND_COLORS, textColor = Constants.BUTTON_TEXT_COLOR, 
        active = false, onClick = function()
            Shop.rerollShop()
        end
    })
end

function Shop.displayUi()
    Shop.openShopButton:show()
end

function Shop.openShop()
    Shop.openShopButton:hide()

    Wait.time(function()
        Shop.closeShopButton:show()
        Shop.rerollShopButton:show()
    end, 0.4)

    -- Not reroll because we don't increment the shop reroll counter
    Shop.discardCurrentShopCards()
    Shop.drawNewShopCards()
end

function Shop.closeShop()
    Shop.closeShopButton:hide()
    Shop.rerollShopButton:hide()
    Wait.time(function()
        Shop.openShopButton:show()
    end, 0.4)

    Shop.discardCurrentShopCards()
end

function Shop.rerollShop()
    -- Check the player has enough coins
    local step = Chapter.getCurrentStep(Chapter.getShopMarker())
    local coins = ResourceCounter.countResource(ResourceCounter.getCoinTile())

    if coins < step then
        broadcastToAll('Not enough coins to reroll shop.', Color.Yellow)
        return
    else
        -- Spend the coins
        ResourceCounter.adjustResource(ResourceCounter.getCoinTile(), -step)
    end

    Shop.discardCurrentShopCards()
    Shop.drawNewShopCards()

    -- Detect current reroll step and increment it if possible
    if step < 5 then
        Chapter.snapToStep(Chapter.getShopMarker(), step + 1)
    end
end

-- Discard all current shop cards
function Shop.discardCurrentShopCards()
    -- For each current shop slot and extra slot, discard the card if it exists
    for color, positions in pairs(Shop.positions) do
        -- Slot
        local card = Utils.getFirstElementAbovePosition(Vector(positions.slot) - Vector(0, 1, 0), Constants.SHOP_CARD)
        if card then
            card.setPositionSmooth(Vector(Shop.positions[Shop.getCardColor(card)].discard) + Vector(0, 1, 0))
            card.setRotationSmooth({0.00, 180.00, 180.00})
        end

        -- Extra slot
        local card = Utils.getFirstElementAbovePosition(Vector(positions.extra_slot) - Vector(0, 1, 0), Constants.SHOP_CARD)
        if card then
            card.setPositionSmooth(Vector(Shop.positions[Shop.getCardColor(card)].discard) + Vector(0, 1, 0))
            card.setRotationSmooth({0.00, 180.00, 180.00})
        end
    end
end

-- Refill shop cards
function Shop.drawNewShopCards()
    -- Mapping from color to the ResultTableau effect that enables the extra shop slot
    local effectNameByColor = {
        [Constants.RED] = Constants.EFFECT_EXTRA_RED_SHOP_SLOT,
        [Constants.GREEN] = Constants.EFFECT_EXTRA_GREEN_SHOP_SLOT,
        [Constants.PURPLE] = Constants.EFFECT_EXTRA_PURPLE_SHOP_SLOT,
    }

    -- For each current shop slot and extra slot, draw a card (even if there is one)
    for color, positions in pairs(Shop.positions) do
        local deck = Utils.getFirstElementAbovePosition(Vector(Shop.positions[color].deck) - Vector(0, 1, 0), 
                                    Constants.SHOP_CARD)
        if deck then
            if deck.type == 'Card' then
                deck.setPositionSmooth(Vector(positions.slot) + Vector(0, 1, 0))
                deck.setRotationSmooth({0.00, 180.00, 0.00})
            else
                deck.takeObject({
                    position = Vector(positions.slot) + Vector(0, 1, 0),
                    rotation = {0.00, 180.00, 0.00},
                    smooth = true,
                })

                -- Check if we have the requirement for the extra slot
                local effectName = effectNameByColor[color]
                if effectName and ResultTableau.getEffectValue(effectName) == 1 then
                    deck.takeObject({
                        position = Vector(positions.extra_slot) + Vector(0, 1, 0),
                        rotation = {0.00, 180.00, 0.00},
                        smooth = true,
                    })
                end
            end
        end
    end
end

function Shop.getCardColor(card)
    if not card then return nil end

    if card.hasTag(Constants.RED) then
        return Constants.RED
    elseif card.hasTag(Constants.GREEN) then
        return Constants.GREEN
    elseif card.hasTag(Constants.PURPLE) then
        return Constants.PURPLE
    end

    return nil
end

function Shop.save()
    local flatSetup = {}

    return flatSetup
end

------------------------------------------------------

return {
    init = Shop.init,
    save = Shop.save,
    displayUi = Shop.displayUi,
    closeShop = Shop.closeShop,
    openShop = Shop.openShop,
}
